# Generated by Django 3.2.16 on 2022-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transum_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mos_sales',
            old_name='ay',
            new_name='fy',
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='purSno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mos_sales',
            name='scriptSno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
