# Generated by Django 3.2.16 on 2022-12-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221126_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mos_sales',
            old_name='ltgc',
            new_name='ltcg',
        ),
        migrations.RenameField(
            model_name='mos_sales',
            old_name='stgc',
            new_name='stcg',
        ),
    ]
